name: deploy
on:
  push:
    branches:
      - '*'
    paths:
      - 'github-runners/**'

permissions:
  id-token: write
  contents: read

jobs:
  tf:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597765856364:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init/plan/apply
        run: |
          terraform -version
          terraform init -input=false
          terraform plan -out tfplan -input=false          
          # terraform apply -input=false -auto-approve tfplan
